language: ruby
rvm:
  - 2.7

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# branch whitelist
branches:
  only:
    - master # test the master branch

cache: bundler # caching bundler gem packages will speed up build

install:
  - bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build
  - bundle exec htmlproofer docs --check-html --empty_alt_ignore --http-status-ignore 999 # For now, ignore 999 error from linkedin links

deploy:
  provider: pages
  local_dir: docs
  target-branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of the repository, as a secure variable
  keep_history: true
  on:
    branch: master # Only deploy when current branch is master
